<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Temperature_Project</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="TempLibrary">
      <HintPath>..\TempLibrary\bin\Debug\net8.0\TempLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
