<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DBcontext\" />
    <Folder Include="Repository\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestApp.Domain\TestApp.Domain.csproj" />
    <ProjectReference Include="..\TestApp.WebAPI\TestApp.WebAPI.csproj" />
  </ItemGroup>

</Project>
